services:
  clickhouse:
    image: bitnami/clickhouse:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8123:8123"
      - "9000:9000"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:${SERVER_PORT}"
    env_file:
      - .env
